services:
  db:
    container_name: postgresql
    image: postgres:17
    restart: unless-stopped
    ports:
      - '5432:5432'
    environment:
      POSTGRES_USER: ${DATABASE_USER}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
      POSTGRES_DB: ${DATABASE_NAME}
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - app-network

  app:
    build:
      context: .
    container_name: node-app
    ports:
      - '5000:5000'
    env_file:
      - ./.env
    depends_on:
      - db
    command: sh -c './start-docker.sh'

volumes:
  postgres-data:

networks:
  app-network:
    driver: bridge
